    version: "3"
    services:
      nginx:
        image: nginx
        container_name: nginx
        ports:
          - "80:80"
        networks:
          - dockerinnernet
        depends_on:
          - "php"
        volumes:
          - /docker/nginx:/etc/nginx/conf.d
          - /docker/www:/var/www/html
      php:
        image: php:5.6-fpm
        container_name: php56
        ports:
          - "9000:9000"
        networks:
          - dockerinnernet
        depends_on:
          - "mysql"
          - "redis"
        volumes:
          - /docker/www:/var/www/html
      mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
          - "3306:3306"
        networks: 
          - dockerinnernet
        volumes:
          - mydata:/var/lib/mysql
          - /docker/dbdump:/root
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
      redis:
        image: redis
        container_name: redis
        ports:
          - "6379:6379"
        networks: 
          - dockerinnernet
        volumes:
          - /docker/redis:/data
      elasticsearch:
        image: elasticsearch:5.3
        container_name: es53
        ports:
          - "9200:9200"
        networks:
          - dockerinnernet
        volumes:
          - /docker/esdata:/usr/share/elasticsearch/data
      logstash:
        image: logstash:5.3
        container_name: logstash53
        depends_on:
          - "elasticsearch"
        networks:
          - dockerinnernet
        ports:
          - "9600:9600"
        volumes:
          - /docker/logstash/pipeline/:/usr/share/logstash/pipelne/
    networks: 
      dockerinnernet:
    volumes:
      mydata: